CREATE TABLE  MAIN_STOCK_GROUP1(
MS_ITEM_ID INT NOT NULL PRIMARY KEY,
MS_ITEM_NAME CHAR(20),
MS_ITEM_DATE DATE,
MS_ITEM_REMARKS CHAR(50),
MS_ITEM_RECEPIENT CHAR(20),
MS_ITEM_QNTY INT,
MS_ITEM_COST FLOAT(2)
);

CREATE TABLE DEPARTMENT_GROUP1(
DEPT_ID INT NOT NULL,
DEPT_NAME CHAR(20)
);

CREATE TABLE DEPARTMENTAL_STOCK_GROUP1(
DS_ITEM_ID INT NOT NULL PRIMARY KEY,
DS_ITEM_NAME CHAR(20),
DS_ITEM_DATE DATE,
DS_ITEM_REMARKS CHAR(50),
DS_ITEM_RECEPIENT CHAR(20),
DS_ITEM_QNTY INT ,
DS_DEPT_ID INT,
DS_ITEM_COST FLOAT(2),
FOREIGN KEY(DS_DEPT_ID) REFERENCES DEPARTMENT_GROUP1(DEPT_ID),
FOREIGN KEY(DS_ITEM_ID) REFERENCES MAIN_STOCK_GROUP1(MS_ITEM_ID)
);
ALTER TABLE DEPARTMENT_GROUP1
ADD PRIMARY KEY(DEPT_ID);

ALTER TABLE MAIN_STOCK_GROUP1
ADD MS_ITEM_SUPPLIER CHAR(20);

DESC MAIN_STOCK_GROUP1
Adding multiple attributes after creating of table
ALTER TABLE MAIN_STOCK_GROUP1
ADD (
MS_ITEM_DESC CHAR(100),
      MS_ITEM_DATE_RECVD DATE,
      MS_ITEM_DEPT_TRANSFERRED INT,
      FOREIGN KEY(MS_ITEM_DEPT_TRANSFERRED) REFERENCES DEPARTMENT_GROUP1(DEPT_ID));
Renaming a column
ALTER TABLE MAIN_STOCK_GROUP1
RENAME COLUMN MS_ITEM_RECEPIENT TO MS_ITEM_RECEPIENT_NAME;
ALTER TABLE MAIN_STOCK_GROUP1
ADD MS_ITEM_RECEPIENT_SIGN CHAR(15);
ALTER TABLE MAIN_STOCK_GROUP1
ADD (
MS_ITEM_VERIFIER_NAME CHAR(20),
MS_ITEM_VERIFIER_SIGN CHAR(20)
);
ALTER TABLE DEPARTMENTAL_STOCK_GROUP1
ADD (
DS_ITEM_VERIFIER_NAME CHAR(20),
DS_ITEM_VERIFIER_SIGN CHAR(20),
DS_ITEM_RECEPIENT_NAME CHAR(20),
DS_ITEM_RECEPIENT_SIGN CHAR(20)
);
DESC DEPARTMENTAL_STOCK_GROUP1
For deleting the whole column
ALTER TABLE DEPARTMENTAL_STOCK_GROUP1
DROP COLUMN DS_ITEM_DATE
ALTER TABLE DEPARTMENTAL_STOCK_GROUP1
ADD(
DS_ITEM_DATE_RECIEVED DATE,
DS_ITEM_DATE__ORDERED DATE
);
DESC DEPARTMENTAL_STOCK_GROUP1
ALTER TABLE DEPARTMENTAL_STOCK_GROUP1
ADD DS_ITEM_SUPPLIER CHAR(15);
DESC MAIN_STOCK_GROUP1
DESC DEPARTMENT_GROUP1
ALTER TABLE DEPARTMENTAL_STOCK_GROUP1
RENAME COLUMN DS_ITEM_DATE__ORDERED TO DS_ITEM_DATE_ORDERED
ALTER TABLE DEPARTMENTAL_STOCK_GROUP1
ADD DS_ITEM_BILL_NUM VARCHAR2(15)
